### ISSUE TITLE
far2l does not build on Mac/Sonoma/M2/ARM64/clang15 since 2c2b6bba5, colorer is a culprit

### ISSUE THREAD

**Issue by rampitec** [elfmz/far2l#2250]
### Discussed in https://github.com/elfmz/far2l/discussions/2249

<div type='discussions-op-text'>

<sup>Originally posted by **rampitec** June  7, 2024</sup>
Guys, do you build it for mac? I used to build for my M2 (arm64), but it starts to fail since colorer upgrade in 2c2b6bba5 on April 21. I fail to understand the error message, this:

/Users/stas/work/far2l/colorer/src/Colorer-library/src/colorer/base/XmlTagDefs.h:75:13: error: array initializer must be an initializer list
const XMLCh hrcTagFilename[] = u"filename\0";

and this:

[9/240] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/xml/LocalFileXmlInputSource.cpp.o
FAILED: Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/xml/LocalFileXmlInputSource.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/stas/work/far2l/utils/include -I/Users/stas/work/far2l/colorer/src/Colorer-library/src -I/Users/stas/work/far2l/_build/Colorer-library/src -isystem /opt/local/include -Wall -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -DWINPORT_REGISTRY  -Wall -fPIC -Wno-unused-function -D_FILE_OFFSET_BITS=64 -O2 -std=c++17 -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk -fvisibility=hidden -fpermissive -Wall -Wextra -Wpedantic -Wsign-promo -Wnon-virtual-dtor -MD -MT Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/xml/LocalFileXmlInputSource.cpp.o -MF Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/xml/LocalFileXmlInputSource.cpp.o.d -o Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/xml/LocalFileXmlInputSource.cpp.o -c /Users/stas/work/far2l/colorer/src/Colorer-library/src/colorer/xml/LocalFileXmlInputSource.cpp
/Users/stas/work/far2l/colorer/src/Colorer-library/src/colorer/xml/LocalFileXmlInputSource.cpp:9:16: error: no matching conversion for functional-style cast from 'const XMLCh *' (aka 'const unsigned short *') to 'UnicodeString'
  auto upath = UnicodeString(path);
               ^~~~~~~~~~~~~~~~~~

To me the syntax 'u"..."' is valid, but the cast to the variable type is not.

The compiler is clang 15.0, language standard is c++11 as written in the CMakeList. Switching to C++17 does not help. Effectively far2l does not build on a modern mac. I wish to fix it, I just do not know what.

I.e., debian support is nice, but it used to work on mac/arm as well before this patch. Should we add a mac builder as well on the github (I saw it working for some projects)?</div>

**Comment by shmuz** [comment]
У меня на GhostBSD собирается, а там clang вроде используется (gcc там нет).

**Comment by rampitec** [comment]
Да блин! Я уже весь мозг сломал. Это не проблема ARM, это совершенно проблема совместммости фронтенда. На маке clang 15, он немножко старый. Но я тут просто пытаюсь понять, на что он вообще ругается и не могу. Исходников 15-го кланга нет, невозможно даже понять, что ему не так! Так-то у меня 19-й кланг, но это ж раздеться, лечь и выпить. Это он у меня в /dev ветке, его еще пойди приспособь к сборке фара.

**Comment by rampitec** [comment]
В смысле, исходники 15-го шланга конечно есть. Нет исходников этого шланга конкретно с патчами под мак. ненавижу тебя, чака!

**Comment by rampitec** [comment]
Парни, давайте реально заведем mac builder? Потому как оно в принципе там работет, но официальная сборка не работает. Я его пару лет как собирал сам, потому что ну cpack не работает. Виснет и все. Или когда не виснет, то то, что оно там сделало, просто тупо закрывается на старте. А если я его собираю, и просто ему cp -R, то работает. Точнее работало до указанного коммита.

**Comment by rampitec** [comment]
Ну и да, доступа к эппловским сборкам шланга у меня нет, я только могу опенсорсный шланг под линуксом гонять, так там все работает.

**Comment by rampitec** [comment]
Просто чтобы вы поняли печаль юзеров маков на арме:

$ gcc --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Это ЖОПА, конечно. Но это жопа, данная нам в ощущениях.

**Comment by ctapmex** [comment]
mac builder - есть, на arm, macos14, clng15 . Вот один из вчерашних прогонов https://github.com/elfmz/far2l/actions/runs/9364725711/job/25778327472 

по ошибкам.
1. const XMLCh hrcTagFilename[] = u"filename\0";  -  не буду пересказывать https://github.com/elfmz/far2l/issues/2230
2. no matching conversion for functional-style cast from 'const XMLCh *' (aka 'const unsigned short *') to 'UnicodeString' auto upath = UnicodeString(path);
тут так же ноги растут из https://github.com/elfmz/far2l/issues/2230

**Comment by rampitec** [comment]
> mac builder - есть, на arm, macos14, clng15 . Вот один из вчерашних прогонов https://github.com/elfmz/far2l/actions/runs/9364725711/job/25778327472

Интересно... Зависимости это что ли... Спасибо.

**Comment by rampitec** [comment]
OK, problem solved. For those interested: I have both macports in /opt/local/ and brew in /opt/homebrew/. Build does not work with macports, so it needs to be removed from PATH before building far.

**Comment by rampitec** [comment]
> mac builder - есть, на arm, macos14, clng15 . Вот один из вчерашних прогонов https://github.com/elfmz/far2l/actions/runs/9364725711/job/25778327472

Кстати спасибо за лог сборки. Именно он и помог понять, что в моей случае было не так.
