### ISSUE TITLE
Support of wxWidgets 3.1

### ISSUE THREAD

**Issue by VVD** [elfmz/far2l#726]
After replace substring "3.0" with "3.1" (wxgtk3u-3.0-config => wxgtk3u-3.1-config and etc.) in several files CMakeLists.txt I got error during build:
```
/tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/WinPort/src/Backend/WX/wxMain.cpp:87:4: error: cannot pass non-trivial object of type 'const wxScopedWCharBuffer' (aka 'const wxScopedCharTypeBuffer<wchar_t>') to variadic function; expected type from format string was 'wchar_t *' [-Wnon-pod-varargs]
                        file.wc_str(), line, func.wc_str(), cond.wc_str(), msg.wc_str());
                        ^~~~~~~~~~~~~
/tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/WinPort/src/Backend/WX/wxMain.cpp:87:25: error: cannot pass non-trivial object of type 'const wxScopedWCharBuffer' (aka 'const wxScopedCharTypeBuffer<wchar_t>') to variadic function; expected type from format string was 'wchar_t *' [-Wnon-pod-varargs]
                        file.wc_str(), line, func.wc_str(), cond.wc_str(), msg.wc_str());
                                             ^~~~~~~~~~~~~
/tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/WinPort/src/Backend/WX/wxMain.cpp:87:40: error: cannot pass non-trivial object of type 'const wxScopedWCharBuffer' (aka 'const wxScopedCharTypeBuffer<wchar_t>') to variadic function; expected type from format string was 'wchar_t *' [-Wnon-pod-varargs]
                        file.wc_str(), line, func.wc_str(), cond.wc_str(), msg.wc_str());
                                                            ^~~~~~~~~~~~~
/tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/WinPort/src/Backend/WX/wxMain.cpp:87:55: error: cannot pass non-trivial object of type 'const wxScopedWCharBuffer' (aka 'const wxScopedCharTypeBuffer<wchar_t>') to variadic function; expected type from format string was 'wchar_t *' [-Wnon-pod-varargs]
                        file.wc_str(), line, func.wc_str(), cond.wc_str(), msg.wc_str());
                                                                           ^~~~~~~~~~~~
4 errors generated.
```

**Comment by elfmz** [comment]
Its not a just compatibility with wx 3.1 problem but with some specific wx build configuration: https://docs.wxwidgets.org/trunk/classwx_string.html#aee28cac512f711f3a41fa3fb3f63d049
Anyway, please try now.

**Comment by VVD** [comment]
Thanks.
This error gone.
But I got other error if pick to build with 3.1:
```
[265/737] cd /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts && gm4 -P -DARCH=FreeBSD\ amd64 /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts/copyright.inc.m4 | gawk -f /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts/enc.awk > /tmp/work/usr/ports/misc/far2l/work/.build/far2l/bootstrap/copyright.inc
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[266/737] cd /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts && gm4 -P -DARCH=FreeBSD\ amd64 /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts/farversion.inc.m4 > /tmp/work/usr/ports/misc/far2l/work/.build/far2l/bootstrap/farversion.inc
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[267/737] cd /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts && gm4 -P -DARCH=FreeBSD\ amd64 /tmp/work/usr/ports/misc/far2l/work/far2l-43057bd/far2l/bootstrap/scripts/farlang.templ.m4 > /tmp/work/usr/ports/misc/far2l/work/.build/far2l/bootstrap/farlang.templ
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
Don't know how it can depends, but with 3.0 build fine…

**Comment by VVD** [comment]
vbuild.sh:    git log -1 --date=format:'%y/%m/%d' --format=%cd-%h

**Comment by VVD** [comment]
During build with 3.0 it show the same errors, but build didn't stopped…

**Comment by VVD** [comment]
This is correct error:
```
lpLNGOutputPath=/tmp/work/usr/ports/misc/far2l/work/.build/far2l/bootstrap
Failed to remove file: './lngd9b4.tmp' errno 2
Failed to remove file: './lngd9b5.tmp' errno 2
Failed to remove file: './lngd9b6.tmp' errno 2
Failed to remove file: './lngd9b7.tmp' errno 2
Failed to remove file: './lngd9b8.tmp' errno 2
Failed to remove file: './lngd9b9.tmp' errno 2
Failed to remove file: './lngd9ba.tmp' errno 2
Failed to remove file: './lngd9b3.tmp' errno 2
Segmentation fault (core dumped)
ninja: build stopped: subcommand failed.
*** Error code 1
```
Core dumped /tmp/work/usr/ports/misc/far2l/work/.build/tools/farlng:
```
Reading symbols from /tmp/work/usr/ports/misc/far2l/work/.build/tools/farlng...
[New LWP 101153]
Core was generated by `/tmp/work/usr/ports/misc/far2l/work/.build/tools/farlng generator -nc -i /tmp/wo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000800ed8430 in ?? () from /usr/local/lib/libwx_baseu-3.1.so.3
(gdb) bt
#0  0x0000000800ed8430 in  () at /usr/local/lib/libwx_baseu-3.1.so.3
#1  0x0000000800f714b8 in wxHashTableBase::DoDelete(wxString const&, long) () at /usr/local/lib/libwx_baseu-3.1.so.3
#2  0x0000000800f8e353 in wxClassInfo::Unregister() () at /usr/local/lib/libwx_baseu-3.1.so.3
#3  0x0000000800f8e2e7 in wxClassInfo::~wxClassInfo() () at /usr/local/lib/libwx_baseu-3.1.so.3
#4  0x000000080122a181 in __cxa_finalize () at /lib/libc.so.7
#5  0x00000008009fc023 in  () at /usr/local/lib/libwx_gtk3u_core-3.1.so.3
#6  0x00007fffffffe060 in  ()
#7  0x0000000800d305b5 in _fini () at /usr/local/lib/libwx_gtk3u_core-3.1.so.3
#8  0x00007fffffffe060 in  ()
#9  0x000000080044e8a3 in  () at /libexec/ld-elf.so.1
#10 0x0000000800472800 in  ()
```

**Comment by elfmz** [comment]
check branch wx31

**Comment by VVD** [comment]
Thanks!
Branch wx31 need several patches to build on FreeBSD:
```
--- CMakeLists.txt.orig
+++ CMakeLists.txt
@@ -38,8 +38,8 @@
 endif()
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
-    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.0-config")
-    set(wxWidgets_wxrc_EXECUTABLE "/usr/local/bin/wxrc-gtk3u-3.0")
+    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.1-config")
+    set(wxWidgets_wxrc_EXECUTABLE "/usr/local/bin/wxrc-gtk3u-3.1")
 endif()
 
 if (NOT ${USEWX})
--- WinPort/CMakeLists.txt.orig
+++ WinPort/CMakeLists.txt
@@ -4,8 +4,8 @@
 find_package(PkgConfig REQUIRED)
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
-    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.0-config")
-    set(wxWidgets_wxrc_EXECUTABLE "/usr/local/bin/wxrc-gtk3u-3.0")
+    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.1-config")
+    set(wxWidgets_wxrc_EXECUTABLE "/usr/local/bin/wxrc-gtk3u-3.1")
 endif()
 
 if (${USEWX})
--- far2l/CMakeLists.txt.orig
+++ far2l/CMakeLists.txt
@@ -167,7 +167,7 @@
 add_dependencies(far2l bootstrap)
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
-    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.0-config")
+    set(wxWidgets_CONFIG_EXECUTABLE "/usr/local/bin/wxgtk3u-3.1-config")
 endif()
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
```
```
--- WinPort/src/APIFSNotify.cpp.orig    2020-06-22 23:39:14 UTC
+++ WinPort/src/APIFSNotify.cpp
@@ -6,6 +6,7 @@
 #include <thread>
 #include <condition_variable>
 #if defined(__APPLE__) || defined(__FreeBSD__)
+# include <sys/types.h>
 # include <sys/event.h>
 # include <sys/time.h>
 #elif !defined(__CYGWIN__)
```
```
--- cmake/modules/FindLibsmbclient.cmake.orig   2020-06-22 23:39:14 UTC
+++ cmake/modules/FindLibsmbclient.cmake
@@ -21,23 +21,17 @@ else (LIBSMBCLIENT_LIBRARIES AND LIBSMBCLIENT_INCLUDE_
   find_path(LIBSMBCLIENT_INCLUDE_DIR
     NAMES
       libsmbclient.h
-    PATHS
-      /usr/include
-      /usr/local/include
-      /opt/local/include
-      /sw/include
     PATH_SUFFIXES
       samba-4.0
+      samba4
   )
 
   find_library(SMBCLIENT_LIBRARY
     NAMES
       smbclient
-    PATHS
-      /usr/lib
-      /usr/local/lib
-      /opt/local/lib
-      /sw/lib
+    PATH_SUFFIXES
+      samba-4.0
+      samba4
   )
 
   if (SMBCLIENT_LIBRARY)
```
And it work fine now!

**Comment by VVD** [comment]
> also do full cmake configure in clean build directory before bulding, to avoid broken build due to prev broken farlng
I remove directory and unpack sources every time before build.

**Comment by VVD** [comment]
I edited patch (with CMakeLists.txt files) in previous comment.
Far2l from branch wx31 with "my" patches build and work fine with both - wx 3.0 and 3.1 on FreeBSD 12.1 amd64.

Why do you install far2l_askpass and far2l_sudoapp direct to /usr/ instead of INSTALL_DIR?
And why in lib/far2l instead of bin?

Please, commit patches to master and make new tag - we can use it for update port for FreeBSD.

**Comment by elfmz** [comment]
eventually i've install freebsd with GUI and applied your changes (and some extra fix for farlng) and found that removing hardcoded pathes to wxgtk3u-3.0-config/wxrc-gtk3u-3.0 breaks cmake
Instead, replacing wxgtk3u-3.0-config with wxgtk3u-3.1-config/wxrc-gtk3u-3.1 works perfectly.
So what in doing wrong?

**Comment by elfmz** [comment]
looks like i have reproducing this issue https://gitlab.kitware.com/cmake/cmake/-/issues/19372
so i'll returned that workaround and made it prefer wx3.1 if its there

**Comment by elfmz** [comment]
also i removed redirection of far2l_sudoapp symlink to ../../bin/far2l cuz it breaks no-install behavior
is this strictly needed?

**Comment by elfmz** [comment]
see all at once here: https://github.com/elfmz/far2l/pull/730

**Comment by VVD** [comment]
Should I work with master or wx31 branch?

**Comment by elfmz** [comment]
now its in master

**Comment by VVD** [comment]
Thanks it work fine with wxWidgets 3.1 on FreeBSD now!
