### ISSUE TITLE
MacOs build issue

### ISSUE THREAD

**Issue by tilperion2** [elfmz/far2l#657]
Hi, I have an issue building Far on MacOs Mojave (10.14.6) and clang:
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Output is:**
`bash-3.2$ make -j4
[  3%] Built target utils
[ 12%] Built target codepages
[ 23%] Built target wineguts
[ 27%] Built target FARStdlib
[ 28%] Built target NetRocks-WebDAV
[ 29%] Built target NetRocks-SFTP
[ 29%] Built target NetRocks-NFS
[ 30%] Built target NetRocks-FILE
[ 36%] Built target WinPort
[ 36%] Built target farlng
eng
rus
hun
languages
dyld: Symbol not found: __ZTISt12length_error
  Referenced from: /Users/user/Projects/far2l/build/tools/farlng
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
 in /Users/user/Projects/far2l/build/tools/farlng
/bin/sh: line 1: 15803 Abort trap: 6           /Users/user/Projects/far2l/build/tools/farlng generator -nc -i /Users/user/Projects/far2l/build/far2l/bootstrap/lang.ini -ol /Users/user/Projects/far2l/build/far2l/bootstrap /Users/user/Projects/far2l/build/far2l/bootstrap/farlang.templ
make[2]: *** [bootstrap] Error 134
make[1]: *** [far2l/bootstrap/CMakeFiles/bootstrap.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ssbarnea** [comment]
Installing using brew worked fine on 10.15 (Catalina) for me.

**Comment by singalen** [comment]
Looks like some library is misconfigured on your system.
Do you have any third-party libraries/compilers?
Did you try a clean rebuild?

The symbol is from standard library:
```
$ c++filt __ZTISt12length_error
typeinfo for std::length_error
```
